# create a conda environment with: `conda env create`
name: mvc
channels:
- defaults
- conda-forge
dependencies:
- python
- nb_conda_kernels
- numpy
- scipy
- pandas
- scikit-learn
- catboost
- scikit-optimize
- altair
- pymc3
- mkl-service
