---
title: "Machine Learning Reduces the Amount of Necessary Maximum Voluntary Isometric Contractions Tests of the Shoulder Muscles"
subtitle: "2018 World Congress of Biomechanics, Dublin"
output:
  bookdown::word_document2:
    reference_docx: template_TF.docx
  bookdown::pdf_document2: default
---

# Introduction
Raw electromyography (EMG) signals are commonly normalized using the maximum voluntary activation (MVA) to provide reliable information on muscle activation levels.
MVA is produced during a maximum voluntary isometric contraction (MVIC) performed in a standardized position.
There is no single MVIC test that produce MVA for all individuals in any given muscle.
Consequently, previous studies have identified optimal combinations of MVIC tests that produce near-to-maximum EMG activation levels on the shoulder complex [1].
However, these recommendations require to perform up to 12 MVIC tests to normalize 12 shoulder muscles.
This study aims to predict shoulder muscle MVA from a limited subset of MVIC tests, without compromising prediction accuracy.

# Methods
The sample included 152 participants. A diversity of 16 MVIC tests and 12 muscles were recorded.
The MVA of each participant and each muscle corresponded to the highest activation produced by previously identified optimal combinations.
The dataset, composed of all activations for all muscles of all participants, was splitted into training (80%) and test (20%) sets.
A random forest regressor was fitted using the training set to evaluate the importance of features and select a subset of the best MVIC tests.
From this subset, an extra-trees regressor was fitted and optimized using a randomized search on hyper parameters.
A non-parametric t-test, coefficient of determination (R2) and root-mean-squared (RMSE) error between predicted value and MVA was computed for each muscle.

# Results
Five MVIC tests were retained. The optimized extra-trees regressor predicts values with a global RMSE and R2 equal to 0.044 mV and 0.95, respectively.
For each muscle, the predicted MVA was not significantly different from the MVA produced by previously identified optimal combinations (Fig. 1).
All muscles but the pectoralis major had R2 superior to 0.8, including seven superior to 0.9.

Fig. 1: Scatter plot of the predicted MVA (mV) against the real MVA for each muscle. RMSE, R2 and p-value are displayed on the upper left of each subplot.

# Discussion
Our preliminary results indicate that a total of five MVIC tests are required to normalize raw EMG signals of 12 shoulder muscles, while 12 tests were needed according to previous recommendations [1].
Machine learning algorithms succeeded in reducing the number of MVIC tests but not at the expense of reliability since the predicted MVA were not significantly different from the MVA produced by previously identified optimal combinations.
The next steps of this study will involve carrying features normalization to provide a relative error and a prediction independent of the EMG system.
The combinations of tests along with the trained model used in this study could be used as guidelines to normalize shoulder muscles EMG signals.

# Reference
1. Dal Maso, F., (2016). Arch Phys Med Rehabil (9): 1542–1551.
